server:
  port: 9005

spring:
  datasource:
    url: jdbc:mysql://localhost/patients?useSSL=false
      username: nacsuser1
      password: nacs
      jpa:
        hibernate:
          ddl-auto: update